services:
  - type: web
    name: gait-emotion-recognition
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gait-emotion-recognition-db-sg
          property: connectionString

databases:
  - name: gait-emotion-recognition-db-sg
    plan: free
    region: singapore
    databaseName: gait_emotion_logs
    user: gait_emotion_app
    ipAllowList: []
